# Data Cleaning

In [1]:
#import libraries

import pandas as pd
import numpy as np

In [2]:
#load files

dataset_df = pd.read_csv('dataset.csv', low_memory=False)
europe_df = pd.read_csv('europe_capitals_population_and_area.csv', sep= ';')
paris_bounding_poligon_df = pd.read_json('paris_bounding_polygon.json')

In [3]:
#find data type counts for each column and store them in a dict

type_value_counts = {}
for column in dataset_df.columns:
    type_value_counts[column] = np.unique(dataset_df[[column]].applymap(type).astype(str).values, return_counts=True)

In [ ]:
for column in type_value_counts.keys():
    print(column)
    for 

## 1. Identify the columns with mixed data types.

In [5]:
#print mixed type columns

print('mixed type columns are as follow:')
for column in type_value_counts.keys():
    if len(type_value_counts[column][1])>1:
        print(column)

mixed type columns are as follow:
region
province
city
claimed
awards
popularity_detailed
popularity_generic
top_tags
price_level
price_range
meals
cuisines
special_diets
features
original_open_hours
default_language
keywords


## 2. For each column, count the number of rows per data type.

In [14]:
type_value_counts

{'restaurant_link': (array(["<class 'str'>"], dtype=object), array([1083397])),
 'restaurant_name': (array(["<class 'str'>"], dtype=object), array([1083397])),
 'original_location': (array(["<class 'str'>"], dtype=object),
  array([1083397])),
 'country': (array(["<class 'str'>"], dtype=object), array([1083397])),
 'region': (array(["<class 'float'>", "<class 'str'>"], dtype=object),
  array([  50323, 1033074])),
 'province': (array(["<class 'float'>", "<class 'str'>"], dtype=object),
  array([340632, 742765])),
 'city': (array(["<class 'float'>", "<class 'str'>"], dtype=object),
  array([400685, 682712])),
 'address': (array(["<class 'str'>"], dtype=object), array([1083397])),
 'latitude': (array(["<class 'float'>"], dtype=object), array([1083397])),
 'longitude': (array(["<class 'float'>"], dtype=object), array([1083397])),
 'claimed': (array(["<class 'float'>", "<class 'str'>"], dtype=object),
  array([   1842, 1081555])),
 'awards': (array(["<class 'float'>", "<class 'str'>"], dtyp

## 3. Would removing missing values solve the mixed data type problem?

### Answer: 

No. Because removing missing values is only possible by deleting rows which would result in loss of data. It is seen that the mixed data type problem is caused by string 'nan' values which should be NaN. Therefore, I mapped string 'nan's to numpy.nan values below which solved the problem.

In [15]:
#fix mixed data type problem by mappint string 'nan' values to numpy.nan

for column in type_value_counts.keys():
    if len(type_value_counts[column]) > 1:
        dataset_df[column] = dataset_df[column].map({'nan':np.nan})

In [16]:
#find data type counts for each column and store them in a dict agagin

type_value_counts = {}
for column in dataset_df.columns:
    type_value_counts[column] = np.unique(dataset_df[[column]].applymap(type).astype(str).values, return_counts=True)

In [17]:
#print mixed type columns after mapping again

print('mixed type columns are as follow:')
for column in type_value_counts.keys():
    if len(type_value_counts[column][1])>1:
        print(column)

mixed type columns are as follow:
